// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvEwDKL1mWv6IAhmvGXMN9_zeK6mVYeqs',
    appId: '1:1039116498343:web:d8fb3cc352a8d0aefcb282',
    messagingSenderId: '1039116498343',
    projectId: 'resource-radar-ai',
    authDomain: 'resource-radar-ai.firebaseapp.com',
    storageBucket: 'resource-radar-ai.firebasestorage.app',
    measurementId: 'G-FG9ET6KNTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdtRr1sCN501zHWurWf0z1xv5ntVKM6o',
    appId: '1:1039116498343:android:52588a01a250edccfcb282',
    messagingSenderId: '1039116498343',
    projectId: 'resource-radar-ai',
    storageBucket: 'resource-radar-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqfYVCVdtp500N4YQGcfU1HqqeIHCV6x0',
    appId: '1:1039116498343:ios:26829185f9a18989fcb282',
    messagingSenderId: '1039116498343',
    projectId: 'resource-radar-ai',
    storageBucket: 'resource-radar-ai.firebasestorage.app',
    iosBundleId: 'com.resourceradar.fieldAgent',
  );
}
